### ISSUE TITLE
Facebook の OAuth 認証のパス

### ISSUE THREAD

**Issue by jimako1989** [jimako1989/hacking_tinder#1]
https://qiita.com/mima_ita/items/439da39b3361fba67a1f

アプリケーションの登録が必要？

**Comment by jimako1989** [comment]
access_token の長さが調べられるサイト
https://developers.facebook.com/tools/debug/accesstoken/

https://gist.github.com/xl1/fe779a817a9d4938193d

手動設定で得られるのは，短い期限のUser Access Token
長い期間にしようとすると，APP SECRET KEYが必要

**Comment by jimako1989** [comment]
iPhoneアプリだと無期限認証となる方法を突いたスクリプトを発見．期限はNeverを確認
```
https://github.com/charliewolf/pynder/issues/99
```

**Comment by jimako1989** [comment]
Added access_token.py to get access_token that is never expired. #6

**Comment by jimako1989** [comment]
FBの認証時にパスワード変更を促されるようになったため，この方法は不可

**Comment by jimako1989** [comment]
```
[root@tk2-220-19741 hacking_tinder]# make test
python3 ./hacking_tinder/test/test_access_token.py nsplat@gmail.com KojimaTadashi1989.facebooK
Traceback (most recent call last):
  File "./hacking_tinder/test/test_access_token.py", line 38, in <module>
    at = AccessToken(email, password)
  File "/root/hacking_tinder/hacking_tinder/main/access_token.py", line 12, in __init__
    self.access_token = self.logic(email, password)
  File "/root/hacking_tinder/hacking_tinder/main/access_token.py", line 24, in logic
    s.submit_form(f, submit=f.submit_fields['__CONFIRM__'])
  File "/usr/lib/python3.5/site-packages/Werkzeug-0.14.1-py3.5.egg/werkzeug/datastructures.py", line 784, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
make: *** [test] Error 1
```

**Comment by jimako1989** [comment]
USER_AGENT をiPhoneXのに変えると，ロック後のパスワード変更は促されなくなった．

**Comment by jimako1989** [comment]
いい加減に面倒なのでfacebookアカウントを別に一つ作ることを検討

**Comment by jimako1989** [comment]
access_token.py のテストを通過させて，CI導入すること

**Comment by tk42** [comment]
facebookアカウントを新たに作ると治った．

**Comment by tk42** [comment]
新しく専用に作ったFacebookアカウントが凍結された
